length :
- value : 24.0
- units : 'in'

diameter :
- value : 0.055
- units : 'in'

power :
- value : 789
- units : 'watts'

volumetric_flow_rate :
- value : 53.9
- units : 'mL/min'

T0 :
- value : 700
- units : 'K'

P0 :
- value : 600
- units : 'psi'

number_of_slices :
 - value : 101
 - units : ''

inlet_composition :
 - value : 'RP2:1.0'
 - units : ''

initial_coverages :
 - value : 'CC(s):1.0'
 - units : ''

reference_temperature :
 - value : 300
 - units : 'K'