length :
- value : 
- units : 

diameter :
- value : 
- units : 

power :
- value : 
- units : 

volumetric_flow_rate :
- value : 
- units : 

T0 :
- value : 
- units : 

P0 :
- value : 
- units : 

number_of_slices :
- value : 
